# For Atom Feed
domain: training.github.com
author: GitHub Training Team
email: training@github.com
title: GitHub Training

# standard jekyll configuration

baseurl: /kit
permalink: /articles/:title
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

menu:
  - title : Home
    url : /
  - title : Support
    url : /support
  - title : Product
    url : url
  - title : Contact
    url : /contact
collections:

include:
- _stylesheets
- _javascript
sass:
  sass_dir: assets/vendor/
  style: :compressed

# Custom site configuration
lang: en
